# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

flutter_application_path = './flutter_imploded'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'InterviewFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  install_all_flutter_pods(flutter_application_path)
  
   use_frameworks!

  # Pods for InterviewFlutter
  pod 'CocoaLumberjack/Swift'

end
